export const browserCoreExamples = [
  "clawcore browser status",
  "clawcore browser start",
  "clawcore browser stop",
  "clawcore browser tabs",
  "clawcore browser open https://example.com",
  "clawcore browser focus abcd1234",
  "clawcore browser close abcd1234",
  "clawcore browser screenshot",
  "clawcore browser screenshot --full-page",
  "clawcore browser screenshot --ref 12",
  "clawcore browser snapshot",
  "clawcore browser snapshot --format aria --limit 200",
  "clawcore browser snapshot --efficient",
  "clawcore browser snapshot --labels",
];

export const browserActionExamples = [
  "clawcore browser navigate https://example.com",
  "clawcore browser resize 1280 720",
  "clawcore browser click 12 --double",
  'clawcore browser type 23 "hello" --submit',
  "clawcore browser press Enter",
  "clawcore browser hover 44",
  "clawcore browser drag 10 11",
  "clawcore browser select 9 OptionA OptionB",
  "clawcore browser upload /tmp/clawcore/uploads/file.pdf",
  'clawcore browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "clawcore browser dialog --accept",
  'clawcore browser wait --text "Done"',
  "clawcore browser evaluate --fn '(el) => el.textContent' --ref 7",
  "clawcore browser console --level error",
  "clawcore browser pdf",
];
